### ISSUE TITLE
don't prevent tabbing when there's no input value

### ISSUE THREAD

**Issue by ksmth** [olahol/react-tagsinput#38] opened 2015-10-01 08:03 UTC
When tabbing through the interface, you get stuck in the input field, even if there's no value. It'd be nice if you could leave the input by hitting the `tab` key in this case.

**Comment by ksmth** [comment] 2015-10-01 08:42
that was quick :dancer:

**Comment by olahol** [comment] 2015-10-01 08:43
Good catch :+1:

**Comment by olahol** [comment] 2015-10-01 08:43
Just doing some light coding with my morning coffee :smile:

**Comment by remyferre** [comment] 2016-05-06 09:44
It seems this feature was removed in version 3. Is it a bug ?

Starting from [this commit](https://github.com/olahol/react-tagsinput/blob/01df702f20c4f751ee2f5cd528098249b819698d/react-tagsinput.js#L116), `handleKeyDown` no longer checks whether the input is empty or not.

**Comment by olahol** [comment] 2016-05-06 09:54
You are right, this is a regression from version 1.

**Comment by olahol** [comment] 2016-05-06 10:01
This is now fixed in version `3.6.1`, thank you @remyferre

**Closed by olahol** 2016-05-06 10:01 UTC

**Comment by remyferre** [comment] 2016-05-06 10:16
Great :smile:  Thanks for the quick response !

**Comment by Zhouzi** [comment] 2016-06-14 16:17
@olahol the bug seems to be back, the tab behavior is prevented even when the input is empty. It's reproducible in the demo: https://olahol.github.io/react-tagsinput/
